internal/command/cluster/connect.go
internal/command/sandbox/create.go
internal/command/sandbox/delete.go

This adds support for the `--output` flag to the `sandbox create` command.
As part of this, I separated log output and sent it to stderr so that it won't get combined with the output JSON/YAML. I also updated other commands to use the same convention of sending log output to stderr for consistency.

sandbox create: Support --output flag.

---

goreleaser.yaml

see
https://stackoverflow.com/questions/66963068/docker-alpine-executable-binary-not-found-even-if-in-path
Without this, running on docker with platform amd64 gave a very mysterious "not found" error for the executable.

fix docker amd/alpine problem

---

internal/command/sandbox/apply.go

This makes more sense in the case of updates and is aligned with
the command name.

change "created' to "applied"

---

internal/config/sandbox.go

Following a discussion about the time it takes to discover a k8s-config error that occurs late and how this is inconvenient for interactive use, this PR proposing reducing the default wait timeout to 3m from 5m.
Rational: most clusters most of the time will probably succeed with 3m, but there will be some failures now and then due to performance bottlenecks.  With 5m, almost all  failures to become ready within the allotted time will be not be due performance bottlenecks.  5m might be a good in-CI default, but 1m would probably be best for interactive use.  Since users are discovering by interactive use, this seems to be a good compromise.  They can up the limit if it starts causing problems in CI due to cluster performance bottlenecks.

reduce-wait-timeout

---

go.mod
go.sum
internal/print/raw.go

always uses a yaml multiline syntax when the string contains multiple lines.
Fixes https://github.com/signadot/signadot/issues/2996

fix yaml output for multiline

---

internal/config/locald.go
internal/locald/sandboxmanager/grpc_server.go
internal/locald/sandboxmanager/sandbox_monitor.go

Fix for, the following bug, reported by @jmsktm :
```
When I initially ran the below sandbox apply command:
signadot sandbox apply -f xxxx --config ~/.signadot/staging.yaml
- When there was a local component: It returned a 401 error
- When I removed the local component: the sandbox was applied successfully
```

Fix problem reading config in local connect, and some other improvements

---

go.mod
go.sum
internal/command/local/connect.go
internal/config/local.go
internal/config/locald.go

see https://github.com/signadot/libconnect/pull/25
Also includes some fixes/improvements:
- cluster is no longer part of ci-config (it is in the connection config)
- mechanism to pass/dump ci-config is improved

support for macos vpn route commands

---

go.mod
go.sum
internal/locald/sandboxmanager/sandbox_monitor.go

this deliberately makes no attempt to consume the new info, as part of prioritising operator changes for release.
depends on https://github.com/signadot/signadot/pull/3438
and https://github.com/signadot/libconnect/pull/26

minimal change to support new tolocal fields from cluster

---

go.mod
go.sum
internal/locald/sandboxmanager/sandbox_manager.go
internal/locald/sandboxmanager/sandbox_monitor.go
internal/locald/sandboxmanager/sandbox_server.go

This has been tested locally against https://github.com/signadot/signadot/pull/3465 and also against the operator in staging without the above changes.  In the latter case, we still observe the delay mentioned in https://github.com/signadot/cli/pull/66#issue-1805317944 . In the former case, there is no delay and substantive updates resolved quickly.  This is the expected resulting behaviour,  and related to https://github.com/signadot/cli/pull/66#discussion_r1265084728

do not update reverse tunnels unless there is a corresponding spec change.

---

internal/command/local/connect.go
internal/command/locald/locald.go
internal/config/locald.go
internal/locald/rootmanager/root_manager.go
internal/locald/rootmanager/sbmgr_monitor.go
internal/locald/run.go

As part of this change, I took away `ConnectInvocationConfig.Unprivileged` which was something specific to the `locald` instance rather than to the whole run.
After connected you will find the following processes:
```bash
$ ps ax | grep "signadot local"
1270041 ?        Sl     0:00 ./signadot locald --root-manager
1270096 ?        Sl     0:00 ./signadot locald --sandbox-manager
```

Addition of the --root-manager and  --sandbox-manager flags to locald

---

internal/locald/sandboxmanager/sandbox_server.go

Here's the current error output
```
23-07-18 scott@air cli % ./signadot sandbox apply -f local-sb.yaml --set cluster=air
Error: unable to apply sandbox in sandboxmanager: rpc error: code = Internal desc = sandbox spec cluster "air" does not match connected cluster ("signadot-staging")
```
Closes #73

check sb cluster matches connected cluster

---

go.mod
go.sum
internal/command/local/connect.go
internal/command/local/printers.go
internal/command/local/status.go
internal/command/locald/locald.go
internal/config/local.go
internal/config/locald.go
internal/config/root.go
internal/locald/api/sandboxmanager/convert.go
internal/locald/rootmanager/pfw_monitor.go
internal/locald/rootmanager/root_manager.go
internal/locald/rootmanager/sbmgr_monitor.go
internal/locald/sandboxmanager/sandbox_manager.go
internal/print/raw.go

These changes include the removal of the strong kubectx dependency (in the case of LB) and also improve `signadot local status` output (as per the discussion in https://signadot.slack.com/archives/C04ST9XTLTC/p1689624722091039.

Remove strong kubectx dependency & improve status

---

go.mod
go.sum
internal/locald/sandboxmanager/revtun.go
local-sb.yaml

incorporate local baseline port as int changes.
This uses go-sdk from branch local-baseline-port-int instead of creating a go-sdk PR because that seems weird to publish the go-sdk when it's not in swagger or the other sdks.

Local baseline port int

---

internal/command/local/connect.go
internal/command/local/disconnect.go
internal/command/local/printers.go
internal/command/local/status.go
internal/config/local.go

when `--wait` is specified, connect will run until the connection is healthy or `--wait-timeout` is reached.  In the case `--wait-timeout` is reached before the connection is healthy, `signadot local connect --wait` will stop the background processes which are trying and failing to establish the connection and exit with a non-zero exit code.
also, disallow `-o` for `signadot local [dis]connect`, before this PR `-o yaml`, etc was a no-op

local connect --wait and --wait-timeout

---

internal/command/local/disconnect.go
internal/command/local/printers.go
internal/config/local.go
internal/locald/sandboxmanager/sdk.go

Implementation of `signadot local disconnect --clean-local-sandboxes`

Clean local sandboxes on disconnect

---

internal/command/local/connect.go
internal/config/local.go

This PR makes `--wait` the default for `signadot local connect` and adds the flag `--no-wait`

Local wait default

---

go.mod
go.sum
internal/locald/sandboxmanager/revtun.go

This depends on https://github.com/signadot/libconnect/pull/53
To have the actual new support, this also depends on and https://github.com/signadot/signadot/pull/4178 and
https://github.com/signadot/signadot/pull/4176
However, this should be harmless and simply continue to fail for no service local workloads on old operators or before the apiserver check change has merged.

support no service local workloads

---

go.mod
go.sum
internal/command/command.go
internal/command/local/connect.go
internal/command/local/disconnect.go
internal/command/local/status.go
internal/command/proxy/connect.go
internal/command/proxy/proxy.go
internal/command/proxy/server.go
internal/config/api.go
internal/config/constants.go
internal/config/proxy.go

Implementation of `signadot proxy connect`:
```bash
$ signadot proxy connect --help
Proxy connections to the specified mappings
Usage:
signadot proxy connect [--sandbox SANDBOX|--routegroup ROUTEGROUP|--cluster CLUSTER] --map <target-protocol>://<target-addr>|<bind-addr> [--map <target-protocol>://<target-addr>|<bind-addr>] [flags]
Flags:
-c, --cluster string      target cluster
-h, --help                help for connect
-m, --map string          --map <target-protocol>://<target-addr>|<bind-addr>
-r, --routegroup string   run the proxy in the context of the specificed routegroup
-s, --sandbox string      run the proxy in the context of the specificed sandbox
Global Flags:
--config string   config file (default is $HOME/.signadot/config.yaml)
--debug           enable debug output
-o, …
```

Proxy implementation

---

internal/command/local/proxy.go

Before:
```bash
$ signadot local proxy --cluster signadot-staging    --map "http://location.hotrod-devmesh:8081|localhost:3332"    --map "grpc://route.hotrod-devmesh:8083|localhost:3333"    --map "tcp://mysql.hotrod-devmesh:3306|localhost:3334"
time=2024-02-29T16:03:07.469-03:00 level=INFO msg="starting TCP proxy" bindAddr=localhost:3334 targetURL=tcp://mysql.hotrod-devmesh:3306
time=2024-02-29T16:03:07.469-03:00 level=INFO msg="starting gRPC proxy" bindAddr=localhost:3333 targetURL=grpc://route.hotrod-devmesh:8083
time=2024-02-29T16:03:07.469-03:00 level=INFO msg="starting HTTP proxy" bindAddr=localhost:3332 targetURL=http://location.hotrod-devmesh:8081
time=2024-02-29T16:03:07.471-03:00 level=ERROR msg="Could not establish connection with proxy" bindAddr=localhost:3332 status-code=403 …
```

Validate cluster parameter in local proxy

---

go.mod
go.sum
internal/command/local/connect.go
internal/command/local/proxy.go

E.g.:
```bash
$ signadot local connect
Error: The connection type ControlPlaneProxy requires operator > v0.15.0
```

Check version skew in local connect

---

go.sum
internal/command/local/connect.go
internal/config/local.go

Upon `local connect` and reconnecting to a broken sandbox, this now gives the below
instead of failing to connect.
I think this is nicer to use, but it also makes the e2e usage of the cli less reliable.
(It seemed spinners aren't particularly well suited to this)
```
24-02-29 scott@air cli % ./signadot local connect
signadot local connect needs root privileges for:
- updating /etc/hosts with cluster service names
- configuring networking to direct local traffic to the cluster
signadot local connect has been started ✓
* runtime config: cluster minikube, running with root-daemon
✓ Local connection healthy!
* operator version 0.15.1-web.5
* port-forward listening at ":50306"
* localnet has been configured
* 24 hosts accessible via /etc/hosts
* sandboxes watcher is running
* Connected …
```

only disconnect for cluster connection issue, not sandbox issues

---

go.mod
go.sum
internal/command/artifact/download.go
internal/command/jobs/printers.go
internal/command/logs/command.go
internal/config/api.go

This PR implements the changes described in https://github.com/signadot/cli/pull/124#discussion_r1633829097.
It is stacked on:
- https://github.com/signadot/go-sdk/pull/49 (required changes in the SDK)
- https://github.com/signadot/cli/pull/126 (minor changes in job logs)
E.g.:
```bash
signadot artifact download --job hotrod-cypress-e2e-ivjkk3y hotrod/cypress/videos/hotrod.cy.js.mp4 -o /tmp/hotrod.cy.js.mp4
File saved successfully at /tmp/hotrod.cy.js.mp4
signadot artifact download --job hotrod-cypress-e2e-ivjkk3y @stdout -o /tmp/stdout
File saved successfully at /tmp/stdout
```

Fix download of artifacts

---

go.mod
go.sum
internal/command/artifact/download.go
internal/command/jobrunnergroup/printers.go
internal/command/jobs/printers.go
internal/command/logs/command.go
internal/config/api.go

This PR:
First fixes a panic in JRG list (when a cluster is disconnected):
```bash
$ signadot jrg list
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xc7965f]
goroutine 1 [running]:
github.com/signadot/cli/internal/command/jobrunnergroup.readiness(...)
/home/ddv/git/signadot/cli/internal/command/jobrunnergroup/printers.go:60
github.com/signadot/cli/internal/command/jobrunnergroup.printRunnerGroupTable(0xc00022d0e0?, {0x1f6cba0?, 0xc00009c028?}, {0xc00022c040, 0x3, 0x0?})
/home/ddv/git/signadot/cli/internal/command/jobrunnergroup/printers.go:38 +0x27f
github.com/signadot/cli/internal/command/jobrunnergroup.list(0xc00015f988, {0x1f6cba0, 0xc00009c028}) …
```

Refactor of job logs

---

internal/command/jobs/printers.go
internal/command/jobs/utils.go

add failed state

---

internal/command/jobs/printers.go
internal/command/jobs/submit.go
internal/command/jobs/utils.go
internal/command/logs/command.go
internal/config/job.go

This PR:
- Stream both `stdout` and `stderr` on `job submit --attach`
- Fixes a bug in `signadot logs --job`:
```bash
$ ./signadot job submit -f /home/ddv/git/signadot/signadot/sandboxes/test/control/data/jobs/basic.yaml
Job basic-hrbd8mq queued on Job Runner Group: basic
Dashboard page: https://app.signadot.com/testing/jobs/basic-hrbd8mq
$ ./signadot logs --job basic-hrbd8mq
Error: 401 Unauthorized: unauthorized    <=======
```

Improve job submit --attach and bug fix

---

internal/locald/rootmanager/tp_monitor.go
internal/locald/sandboxmanager/sdk.go

This is intended as minimal change to fix
https://github.com/signadot/signadot/issues/5172
tested with warp, it causes restarts and we are able to connect whereas previously it hangs
regarding discussion around:
- do we need to make this visible in status?
I changed it so that it is more visible in status, returning unhealthy when a restart is needed instead of healthy.
- do we need to make check period configurable?
I think not, because it is actually complicated because there 2 check periods for healthy and unhealthy state.  Also, the check period relates to the timeout for the added checking request.

add check to access agent-metrics endpoint

---

internal/command/jobs/submit.go
internal/config/job.go

```
24-12-30 scott@air cli % cat ~/tmp/job.yaml
spec:
namePrefix: jwait
runnerGroup: scott-jrg
script: |
#!/bin/sh
echo not exiting-28
24-12-30 scott@air cli % ./signadot job submit -f ~/tmp/job.yaml --wait
Job jwait-lfl0zyi succeeded on Job Runner Group: scott-jrg
Dashboard page: https://app.signadot.com/testing/jobs/jwait-lfl0zyi
24-12-30 scott@air cli % echo $?
0
```
```
24-12-30 scott@air cli % cat ~/tmp/job.yaml
spec:
namePrefix: jwait
runnerGroup: scott-jrg
script: |
#!/bin/sh
echo exiting-28
exit 28
24-12-30 scott@air cli % ./signadot job submit -f ~/tmp/job.yaml --wait
Job jwait-k3mbgby failed on Job Runner Group: scott-jrg
Dashboard page: https://app.signadot.com/testing/jobs/jwait-k3mbgby
Error: job "jwait-k3mbgby" failed
24-12-30 scott@air cli % echo $?
1
```
```
24-12-30 …
```

addition of `signadot job submit -f ... --wait`

---

internal/command/command.go
internal/command/hostedtest/apply.go
internal/command/hostedtest/command.go
internal/command/hostedtest/delete.go
internal/command/hostedtest/get.go
internal/command/hostedtest/list.go
internal/command/hostedtest/print.go
internal/command/hostedtest/run.go
internal/command/test/command.go
internal/config/hostedtest.go

Stacked on https://github.com/signadot/cli/pull/161.
This PR:
* Renames `syntheric` to `hosted-test`
* Makes `test` command public

Rename synthetic to hosted-test

---

internal/command/smarttest/printers.go
internal/command/smarttest/run_output.go

without this, there is greater risk of going up the wrong number of lines to overwrite each entry with yacspin

truncate the output of wait

---

README.md

The current link redirects to https://www.signadot.com/docs/cli, which gives a 404.

chore: Fix broken usage guide link in README.md

---

go.mod
go.sum
internal/auth/auth.go
internal/command/local/proxy.go
internal/locald/sandboxmanager/sandbox_manager.go

Depends on https://github.com/signadot/signadot/pull/5754, https://github.com/signadot/libconnect/pull/98.
Fix `bearer-token` auth when using `controlplaneproxy`.

Fix bearer-token auth in controlplaneproxy

---

go.mod
go.sum
internal/command/auth/login.go
internal/config/api.go

Depends on:
- https://github.com/signadot/go-sdk/pull/65
- https://github.com/signadot/signadot/pull/5774
This PR uses the `/api/v2/orgs` endpoint to resolve Orgs (instead of getting it from `/auth/device/token`).

Refactor of auth/device/token API

---

internal/command/smarttest/command.go
internal/command/smarttest/execution.go
internal/command/smarttest/execution_list.go
internal/command/smarttest/list.go
internal/command/smarttest/run.go
internal/config/smarttest.go
internal/repoconfig/config.go
internal/repoconfig/finder.go

This PR adds the ability to filter the local tests by label by
1. Adding a new subcommand `signadot st list` which lists test files; and
2. Adding all the flags of `signadot st list` to `signadot st run`, so that the selected test files will be run
```
25-05-12 scott@air cli % ./signadot st -h
Signadot smart tests
Usage:
signadot smart-test [command]
Aliases:
smart-test, st
Available Commands:
execution   Work with smart test executions
list        List local tests
run         Run tests
Flags:
-h, --help   help for smart-test
Global Flags:
--config string   config file (default is $HOME/.signadot/config.yaml)
--debug           enable debug output
-o, --output string   output format (json|yaml)
Use "signadot smart-test [command] --help" for more information about a command.
```
``` …
```

add label selection and local listing to `signadot st`

---

internal/command/sandbox/get_utils.go

This fixes a nil pointer exception when accessing a custom overriden secret value.

fix get-env secret

---

internal/command/sandbox/printers.go

```
25-07-22 scott@air cli % ./signadot sb list
NAME                             ROUTING KEY     DESCRIPTION           CLUSTER         CREATED        STATUS
scott-tests-demo                 xplzwz3xfd4ww                         v0.19.0-xrc.1   9 months ago   Not Ready
demo-create-get-delet-7f08fcfd   ud036luckucfl   No-Op sandbox fo...   v0.19.0-xrc.1   9 months ago   Not Ready
25-07-22 scott@air cli % ./signadot sb get scott-tests-demo
Name:             scott-tests-demo
Routing Key:      xplzwz3xfd4ww
Description:
Cluster:          v0.19.0-xrc.1
Created:          Thu, 24 Oct 2024 10:48:51 CEST (9 months ago)
Updated:          Mon, 07 Jul 2025 11:18:35 CEST (2 weeks ago)
TTL:              - (forever)
Dashboard page:   https://app.signadot.com/sandbox/name/scott-tests-demo
Status: …
```

rename sandbox ID and add routing key to list output
