- internal/command/sandbox/printers.go
> Rename 'Preview Endpoint' column.

- internal/command/sandbox/apply.go
- internal/command/sandbox/delete.go
- internal/command/sandbox/subst.go
- internal/command/sandbox/subst_test.go
- internal/config/flag_types.go
- internal/config/sandbox.go
This has been manually tested for
- concatenation
- multiple keys
- unbound vars
- command line usage errors
- port automatic int conversion
Some items are still under discussion, such as the exact syntax of the variables, but this is a good enough start that I'll make it a non-draft.
> add scalar substition support

- Dockerfile
- Makefile
- goreleaser.yaml
This PR adds linux docker images (arm/amd64 so they should run on Mac/arm under docker) to the build/release.
> publish linux docker images

- internal/buildinfo/buildinfo.go
- internal/command/bug/bug.go
- internal/command/cluster/command.go
- internal/command/command.go
- internal/command/sandbox/command.go
- internal/config/api.go
- internal/config/cluster.go
- internal/config/root.go
- internal/config/sandbox.go
example output:
```
Opening browser to https://github.com/signadot/community/issues/new?assignees=&labels=bug&template=bug_report.md&title=%5Bbug%5D in 5s.  Please copy and paste the
following into the bug report:
{
"Debug": false,
"ConfigFile": "",
"Org": "signadot",
"MaskedAPIKey": "1bgPGB...",
"APIURL": "https://api.staging.signadot.com"
}
```
> Bug report command

- internal/command/sandbox/delete.go
- internal/command/sandbox/subst_test.go
- internal/config/sandbox.go
This PR adds force delete functionality to the CLI.
> add force delete

- internal/command/sandbox/printers.go
22-10-24 scott@pavillion cli % ./dist/signadot_darwin_arm64/signadot sandbox get foxish-ttl
ID:               3thnkg09f9w0q
Name:             foxish-ttl
Description:      sandbox env ttl of 20 days
Cluster:          signadot-staging
Created:          Fri, 21 Oct 2022 00:11:45 CEST (3 days ago)
TTL:              Wed, 09 Nov 2022 23:11:45 CET (2 weeks)
Dashboard page:   https://app.signadot.com/sandbox/id/3thnkg09f9w0q
Status:           Ready (AllDesiredForksReady: All desired workloads are available.)
SANDBOX ENDPOINT    TYPE   URL
route-endpoint      fork   https://route-endpoint--foxish-ttl.preview.staging.signadot.com
frontend-endpoint   host   https://frontend-endpoint--foxish-ttl.preview.staging.signadot.com
22-10-24 scott@pavillion cli % ./dist/signadot_darwin_arm64/signadot sandbox …
> print out ttl on sandbox get

- go.mod
- go.sum
- internal/command/resourceplugin/subst.go
- internal/command/routegroup/subst.go
- internal/command/sandbox/subst.go
- internal/config/flag_types.go
- internal/utils/subst_test.go
- internal/utils/template.go
- internal/utils/template_parser_test.go
```
$ cat template.yaml
name: "@{name}"
spec:
description: 'This is just a multistep sample plugin'
runner:
image: ubuntu
namespace: signadot
podTemplateOverlay: "@{embed:pod-template-overlay.yaml}"
create:
- name: provision
inputs:
- name: dbname
valueFromSandbox: true
outputs:
- name: dbhost
from: "/tmp/dbhost"
- name: dbpass
from: "/tmp/dbpass"
script: "@{embed:provision.sh}"
- name: setup
inputs:
- name: dbhost
valueFromStep:
name: provision
output: dbhost
- name: dbpass
valueFromStep:
name: provision
output: dbpass
- name: dbname
valueFromSandbox: true
outputs:
- name: user-id
from: "/tmp/user-id"
script: "@{embed:setup.sh}"
delete:
- name: deprovision
inputs:
- name: dbhost
valueFromStep:
name: provision
output: dbhost
- name: dbpass
valueFromStep:
name: provision
output: dbpass
- …
```
> #2986 Support embedding content from file

- internal/utils/template.go
Just wanted to follow up to your post-merge review.  PTAL and approve+merge if it looks ok to you.
> CR followup: naming

- go.mod
- go.sum
- internal/locald/sandboxmanager/sandbox_manager.go
This is related with the following changes https://github.com/signadot/libconnect/pull/28
> Integration with revtun config labels

- go.mod
- go.sum
see https://github.com/signadot/libconnect/pull/39
and https://github.com/signadot/signadot/issues/3877
> use libconnect fixes for /etc/hosts under docker

- .github/workflows/release.yaml
- README.md
> GHA for releaser

- go.mod
- go.sum
- internal/locald/rootmanager/root_manager.go
depends on https://github.com/signadot/libconnect/pull/41
> filter out excluded cidrs from /etc/hosts

- go.mod
- go.sum
- internal/command/local/connect.go
- internal/config/local.go
- internal/config/locald.go
- internal/locald/rootmanager/pfw_monitor.go
- internal/locald/rootmanager/root_manager.go
Sharing this now as it completes my first end to end test, but leaving as draft to clean up and test more.
consumes the various libconnect PRs and operator tunnel-api PRs
(top of stack libconnect is https://github.com/signadot/libconnect/pull/47 and operator https://github.com/signadot/signadot/pull/4157)
> first working local ip mappings

- internal/command/local/proxy.go
- internal/config/local.go
(e2e PR forthcoming... then I'll update the docs PRs)
> use @ instead of | in proxy mapping specs

- README.md
- scripts/install.sh
Install the CLI with:
```sh
curl -sSLf https://raw.githubusercontent.com/signadot/cli/main/scripts/install.sh | sh
```
> Addition of an installation script

- internal/command/logs/command.go
fixes local dev,
also looks more correct (host/path/etc)
> changes to job logs url formatting

- internal/command/jobs/printers.go
This fixes https://github.com/signadot/signadot/issues/4461
> fix environment field

- go.mod
- go.sum
- internal/command/jobs/printers.go
Depends on https://github.com/signadot/go-sdk/pull/47
> incorporate the split of completed phase into failed/succeeded

- internal/command/jobrunnergroup/printers.go
This PR improves behavior from:
```bash
$ signadot jrg apply -f  /home/ddv/git/signadot/signadot/sandboxes/test/control/data/jobrunnergroups/basic.yaml 
Applied runner "basic" ("https://app.signadot.com/testing/runner-groups/basic")
$ signadot job submit -f /home/ddv/git/signadot/signadot/sandboxes/test/control/data/jobs/basic.yaml
Job basic-10r273y queued on Job Runner Group: basic
Dashboard page: https://app.signadot.com/testing/jobs/basic-10r273y
$ signadot jrg delete basic
Deleted jobrunnergroup "basic".
$ signadot jrg list
NAME      CLUSTER   CREATED          STATUS
cypress   test      2 days ago       1/1 pods ready
basic     test      27 seconds ago   1/1 pods ready   <=======
```
To:
```bash
$ signadot jrg apply -f  /home/ddv/git/signadot/signadot/sandboxes/test/control/data/jobrun …
```
> Contemplate draining state in JRG default display

- internal/command/jobs/printers.go
Fixes https://github.com/signadot/cli/issues/136
But i also notice one issue, since the job is really short, the logs are not print out
> fix typo submit

- internal/command/sandbox/apply.go
- internal/command/sandbox/printers.go
- internal/config/root.go
This also fixes https://github.com/signadot/signadot/issues/4768
> replace sandbox id wording

- internal/command/smarttest/printers.go
- internal/command/smarttest/run_output.go
E.g.:
```bash
$ signadot st run -d tests/fixtures/smart-tests-git/backend/  --sandbox=daniel-tests-demo
Created test run with ID "ehwn70y3oykg" in cluster "test".
Test run status:
✅   github.com/signadot/cli/tests/fixtures/smart-tests-git/backend/team2/file2.star   [ID: ehwn70y3oykg-1, STATUS: completed]
✅   github.com/signadot/cli/tests/fixtures/smart-tests-git/backend/test.star          [ID: ehwn70y3oykg-2, STATUS: completed]
✅   github.com/signadot/cli/tests/fixtures/smart-tests-git/backend/team1/file1.star   [ID: ehwn70y3oykg-3, STATUS: completed]
Test run summary:
* Executions
✅ 3/3 tests completed
* Diffs
✅ No high/medium relevance differences found
* Checks
✅ 1 checks passed
```
```bash
$ signadot smart-test execution list --run-id ehwmcqwqphq8
ID               SOURCE     TESTNAME …
```
> Smart tests final touches

- internal/config/smarttest.go
This makes it uniform with the file format
> use key=value for --set-label

- internal/command/smarttest/execution_cancel.go
- internal/command/smarttest/execution_get.go
- internal/command/smarttest/execution_list.go
- internal/config/smarttest.go
This is an extension to https://github.com/signadot/cli/pull/171 + some text improvements.
> Smart test label normalization

- go.mod
- go.sum
- internal/command/sandbox/get_env.go
- internal/command/sandbox/get_files.go
- internal/command/sandbox/get_utils.go
- internal/locald/sandboxmanager/sdk.go
Depends on https://github.com/signadot/libconnect/pull/103
> Local env polish

- go.mod
- go.sum
- internal/repoconfig/git.go
depends on https://github.com/signadot/libconnect/pull/106
> use libconnect w/ namespace fix

- internal/command/sandbox/get_env.go
easy improvement from request from Arjun for demo: add downward api
> add downward API to get-env output
